# ---------------------------------------------------------------------------
# ghstats CLI GitHub Actions CI build.
# ---------------------------------------------------------------------------
name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    types:
      - opened
      - synchronize
      - committed
    branches-ignore:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Go Modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Code Review
      shell: bash
      run: |
        make clean golangci

    - name: Unit Tests
      shell: bash
      run: make test-ghstats

    - name: build
      shell: bash
      run: make clean ghstats

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-output
        path: build/_output/test-logs
