# ---------------------------------------------------------------------------
# ghstats CLI GitHub Actions CI build.
# ---------------------------------------------------------------------------
name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    types:
      - opened
      - synchronize
      - committed
    branches-ignore:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

#   Checkout the source, we need a depth of zero to fetch all of the history otherwise
#   the copyright check cannot work out the date of the files from Git.
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Go Modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-mods-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mods-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Code Review
      shell: bash
      run: |
        make clean golangci

    - name: Unit Tests
      shell: bash
      run: make test

    - name: Build
      shell: bash
      run: make clean ghstats

    - name: Make for all Platforms
      shell: bash
      run: make ghstats-all
      
    - name: Upload Linux amd64
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-linux-amd64
        path: bin/linux/amd64/ghstats

    - name: Upload Linux arm64
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-linux-arm64
        path: bin/linux/arm64/ghstats

    - name: Upload Linux 386
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-linux-386
        path: bin/linux/386/ghstats

    - name: Upload Windows amd64
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-windows-amd64
        path: bin/windows/amd64/ghstats.exe

    - name: Upload Windows arm
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-windows-arm
        path: bin/windows/arm/ghstats.exe

    - name: Upload Mac amd
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-darwin-amd
        path: bin/darwin/amd64/ghstats

    - name: Upload Mac arm
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: ghstats-darwin-arm
        path: bin/darwin/arm64/ghstats

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: test-output
        path: build/_output/test-logs
